config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cuisines, only: [:index]
  resources :matches, only: [:index, :create, :destroy]

  delete '/cuisines/:cuisine_id/destroy_match', to: 'matches#destroy', as: :match_destroy

  resources :favorite_cuisines, only: [:create, :destroy] do
    collection do #removing the ID in the url <> member which shos the ID
      get 'add'
    end
    get 'compare'
    get 'uncompare'
  end

  get 'results', to:'trends#results'
  get 'comparison', to:'pages#comparison'
  get 'map', to:'trends#map'
  get 'graph', to:'trends#graph'
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  has_many :restaurant_cuisines, dependent: :destroy
  has_many :restaurants, through: :restaurant_cuisines, dependent: :destroy

  has_many :favorite_cuisines
  has_many :trends, dependent: :destroy
  # validates :name, presence: true
  # validates :photo, presence: true

  def self.with_photo
    Cuisine.all.where.not(photo: nil).order(:name)
  end

  def av_attendance(_city, season)
    # get the scaled attendance for the months that match the input
    # if end_month lower than start_month, then iterate year by one
    attendance = 0
    season.each do |month_name|
      attendance += trends.where("month like ?", "#{month_name}%").sum(:scaled_attendance)
    end
    if restaurants.count == 0
      average_attendance = 0
    else
      average_attendance = attendance / restaurants.count
    end
    return average_attendance
  end

  def av_rating
    if restaurants.count != 0
      (restaurants.sum(:rating)/restaurants.count.to_f).round(2)
    end
  end

  def av_price_range
    if restaurants.count != 0
      (restaurants.sum(:price_range)/restaurants.count.to_f).round(0)
    end
  end

  def no_restaurants
    restaurants.count
  end

  def trend_data
    query = 'date in '
    trends.order(:date).map { |trend| [trend.date, trend.scaled_attendance.to_i] }.select do |trend|
      ["2017", "2018", "2019"].any? do |year|
        trend[0].first(4).include?(year)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorite_cuisines
  has_many :cuisines, through: :favorite_cuisines
  has_many :matches, dependent: :destroy
  has_many :matched_cuisines, through: :matches, source: :cuisine, class_name: 'Cuisine'

  def matched?(cuisine)
    matched_cuisines.pluck(:id).include?(cuisine.id)
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  def index
    session[:city] = params[:city]
    session[:start_period] = params[:start_period]
    session[:end_period] = params[:end_period]

    update_ranking_in_cuisines

    @cuisines = Cuisine.with_photo
    current_user.favorite_cuisines.destroy_all
  end

  private

  def update_ranking_in_cuisines
    cuisines = Cuisine.all.sort_by do |cuisine|
      cuisine.av_attendance(params[:city], selected_season(params[:start_period], params[:end_period]))
    end.reverse

    cuisines.each.with_index do |cuisine, index|
      cuisine.update_column(:ranking, index + 1)
    end
  end

  def selected_season(start_period, end_period)
    start = start_period.to_i
    finish = end_period.to_i
    if finish < start
      season_months = (start..12).to_set.merge(1..finish)
    else
      season_months = (start..finish)
    end
    season_months.map do |month_number|
      Date::ABBR_MONTHNAMES[month_number]
    end
  end
end

app/views/cuisines/index.html.erb
<div class="rectangle-white no-margin-no-padding">
  <div class="container">
    <div style="padding:50px 0px 30px 0px;">
      <h1><strong>Type of food</strong></h1>
      <h4 class="top-text-page-black mb-5">What type of food would you like to cook? Let's select the ones you like 🤤🤤🤤</h4>

      <div id="create-favorites-form">
        <%= form_for current_user, url: favorite_cuisines_path, method: :post do |f| %>

          <%= f.collection_check_boxes :cuisine_ids , @cuisines, :id, :name, item_label_class: 'my-custom-class'   %>
          <%= f.submit 'Submit >', class: "btn btn-lg btn-yellow" %>
        <% end %>
      </div>
    </div>


    <div class=" container rectangle-light-gray mt-2 pt-4 px-4 d-flex flex-wrap justify-content-between">
      <% @cuisines.each do |cuisine| %>
        <div data-id="<%= cuisine.id %>" class="mb-3 hover-darker-cuisine-card cuisine-card">
          <div class="darker-cuisine-card">
            <%= image_tag "#{cuisine.photo}", class: "small-cuisine-card-image", alt: "#{cuisine.name}" %>
            <div class="to-select"></div>
            <div class="d-flex align-items-end">
              <p class="small-cuisine-card-name-fav-page"> <%= cuisine.name %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>