config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cuisines, only: [:index]
  resources :matches, only: [:index, :create, :destroy]

  delete '/cuisines/:cuisine_id/destroy_match', to: 'matches#destroy', as: :match_destroy

  resources :favorite_cuisines, only: [:create, :destroy] do
    collection do #removing the ID in the url <> member which shos the ID
      get 'add'
    end
    get 'compare'
    get 'uncompare'
  end

  get 'results', to:'trends#results'
  get 'comparison', to:'pages#comparison'
  get 'map', to:'trends#map'
  get 'graph', to:'trends#graph'
end

app/models/trend.rb
class Trend < ApplicationRecord
  belongs_to :city
  belongs_to :cuisine #, dependent: :destroy

  # # validates :location, presence: true
  # # validates :cuisine_trend, presence: true
  # validates :month, presence: true
  # validates :value, presence: true
  # validates :city, presence: true
  # validates :cuisine, presence: true

  def self.attendance(city)
    Trend.where(city_id: 1).sum(:moving_average).round(0) # to be changed
  end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  before_action :fetch_city
  before_action :threshold
  before_action :attendance_array, only: [:map]
  before_action :rating_array, only: [:map]
  before_action :price_array, only: [:map]
  before_action :competitors_array, only: [:map]
  before_action :trend_indication, only: [:map]

  def results
    @season = selected_season(session[:start_period], session[:end_period])

    if params[:query].present?
      #  sort by name
      @favoritecuisines = []
      filter = params[:query].to_sym
      @userfavorite = current_user.favorite_cuisines
                                      .map(&:cuisine) # map(|cuisine| cuisine)
                                      .sort_by(&filter)
                                      # sort_by { |c| c.attendance(@city))}.reverse
      @userfavorite.each do |fav|
        @favoritecuisines << current_user.favorite_cuisines.where(cuisine_id: fav.id).first
      end
      # @unselectedcuisines = Cuisine.with_photo.where.not(id: @favoritecuisines.pluck(:cuisine_id))
      # @comparisoncuisines = @favoritecuisines.select { |fav| fav.compare == true }

    elsif params[:metrics].present?
      # sort by all metrics which are numbers exept attendance
      @favoritecuisines = []
      filter = params[:metrics].to_sym
      @userfavorite = current_user.favorite_cuisines
                                      .map(&:cuisine)
                                      .sort_by(&filter)
                                      # sort_by { |c| c.attendance(@city))}.reverse
      @userfavorite.each do |fav|
        @favoritecuisines << current_user.favorite_cuisines.where(cuisine_id: fav.id).first
      end
      # @unselectedcuisines = Cuisine.with_photo.where.not(id: @favoritecuisines.pluck(:cuisine_id))
      # @comparisoncuisines = @favoritecuisines.select { |fav| fav.compare == true }
      @favoritecuisines.reverse!

    else params[:attendance].present?
      #  sort by attendance
      @favoritecuisines = []
      @userfavorite = current_user.favorite_cuisines
                                      .map(&:cuisine)
                                      .sort_by { |c| c.av_attendance(@city,@season) }.reverse
      @userfavorite.each do |fav|
        @favoritecuisines << current_user.favorite_cuisines.where(cuisine_id: fav.id).first
      end
      # @unselectedcuisines = Cuisine.with_photo.where.not(id: @favoritecuisines.pluck(:cuisine_id))
      # @comparisoncuisines = @favoritecuisines.select { |fav| fav.compare == true }

    # else
    #   @favoritecuisines = current_user.favorite_cuisines
    end
      # @unselectedcuisines = Cuisine.with_photo.where.not(id: @favoritecuisines.pluck(:cuisine_id)).sort_by { |c| c.av_attendance(@city, @season) }.reverse
      @unselectedcuisines = Cuisine.with_photo.sort_by { |c| c.av_attendance(@city, @season) }.reverse
      @comparisoncuisines = @favoritecuisines.select { |fav| fav.compare == true }
      @cuisines = Cuisine.all.sort_by { |c| c.av_attendance(@city, @season) }.reverse
  end

  def map
    @cuisine = Cuisine.find(params[:cuisine_id])
    @season = params[:season]
    @restaurants = @cuisine.restaurants.where(city: @city)
    @geojson = build_geojson
    @markers = @restaurants.map do |r|
      {
        lat: r.latitude,
        lng: r.longitude
      }
    end

  end

  def graph
    @season = params[:season]
    @cuisines = current_user.favorite_cuisines.map(&:cuisine).sort_by { |c| c.av_attendance(@city, @season) }.reverse

    @cuisines_map = @cuisines.map do |cuisine|
      {
        name: cuisine.name,
        data: cuisine.trend_data
      }
    end
  end

  private

  def fetch_city
    @city = City.where(name: "Sydney").first
  end

  def build_geojson
    {
      type: "FeatureCollection",
      features: @restaurants.map(&:to_feature)
    }
  end

  def selected_season(start_period, end_period)
    start = start_period.to_i
    finish = end_period.to_i
    if finish < start
      season_months = (start..12).to_set.merge(1..finish)
    else
      season_months = (start..finish)
    end
    season_months.map do |month_number|
      Date::ABBR_MONTHNAMES[month_number]
    end
  end

  def attendance_array
    @season = params[:season]
    @cuisines_sorted_by_attendance = Cuisine.all.sort_by {|c| c.av_attendance(@city, @season) }.reverse
    @cuisine_attendance_array = @cuisines_sorted_by_attendance.map { |c| c.av_attendance(@city, @season) }
    @threshold_attendance_top = @cuisine_attendance_array[@high_percentile_index]
    @threshold_attendance_bottom = @cuisine_attendance_array[@low_percentile_index]
  end

  def rating_array
    @cuisines_sorted_by_attendance = Cuisine.all.sort_by {|c| c.av_attendance(@city, @season) }.reverse
    @cuisine_rating_array = @cuisines_sorted_by_attendance.map { |c| c.av_rating }
    @average_top_rating = @cuisine_rating_array.first(@high_percentile_index).sum/@high_percentile_index
    @average_mid_rating = @cuisine_rating_array[@high_percentile_index..@low_percentile_index].sum/@low_percentile_index
  end
  def competitors_array
    @cuisines_sorted_by_attendance = Cuisine.all.sort_by {|c| c.av_attendance(@city, @season) }.reverse
    @cuisine_no_competitors_array = @cuisines_sorted_by_attendance.map {|c| c.no_restaurants}
    @average_top_competitors = @cuisine_no_competitors_array.first(@high_percentile_index).sum/@high_percentile_index
    @average_mid_competitors = @cuisine_no_competitors_array[@high_percentile_index..@low_percentile_index].sum/@low_percentile_index
  end
  def price_array
    @cuisines_sorted_by_attendance = Cuisine.all.sort_by {|c| c.av_attendance(@city, @season) }.reverse
    @cuisine_price_array = @cuisines_sorted_by_attendance.map { |c| c.av_price_range }
    @average_top_price = @cuisine_price_array.first(@high_percentile_index).sum/@high_percentile_index
    @average_mid_price = @cuisine_price_array[@high_percentile_index..@low_percentile_index].sum/@low_percentile_index
  end
  def trend_indication
    @av_trend_current_year = Trend.all.where(cuisine_id: params[:cuisine_id]).where("month like ?","%#{Time.now.year}%").sum(:scaled_attendance)/9
    @av_trend_previous_year = Trend.all.where(cuisine_id: params[:cuisine_id]).where("month like ?","%#{Time.now.year - 1}%").sum(:scaled_attendance)/12
    if @av_trend_previous_year!=0 && @av_trend_current_year / @av_trend_previous_year > 1.05
      @trend = "increasing ↗️"
    elsif @av_trend_previous_year!=0 && (@av_trend_current_year / @av_trend_previous_year < 1.05 || @av_trend_current_year / @av_trend_previous_year > 0.95)
      @trend = "stable ➡️"
    elsif @av_trend_previous_year!=0 && @av_trend_current_year / @av_trend_previous_year < 0.95
      @trend = "decreasing ↘️"
    else
      @trend = "No trend"
    end
  end
  def threshold
    @high_percentile_index = Cuisine.all.count/3.to_i-1
    @low_percentile_index = Cuisine.all.count/4*3.to_i-1
  end


  def recommendation
    if @cuisines_sorted_by_attendance.first(@high_percentile_index).include? (@cuisine)
      high_end_cuisine
    else
      low_end_cuisine
    end
  end

  def high_end_cuisine
    attendance = @cuisine.av_attendance(@city, @season)
    case attendance
    when attendance / @threshold_attendance_top > 1.25
      @attendance_evaluation = "the attendance for #{@cuisine} is #{((attendance / @threshold_attendance_top)* 100).floor - 100 } higher the the average top ranked restaurant"
    when attendance / @threshold_attendance_top > 1.1
      @attendance_evaluation = "the attendance for #{@cuisine} is #{((attendance / @threshold_attendance_top)* 100).floor - 100 } higher the the average top ranked restaurant"

    end
  end

  def low_end_cuisine
    @results = "results low"
  end

end

app/views/trends/graph.html.erb
<div class="m-5">
  <%=  link_to results_path, class: 'small-cuisine-card-name-gray' do %>
    |<i class="fas fa-arrow-left"></i> Back
  <% end %>
  <div class="row mt-3">
    <div class="col-6">
      <% current_user.favorite_cuisines.map(&:cuisine).sort_by { |c| c.av_attendance(@city, @season) }.reverse.each do |cuisine| %>
        <div class="card-product m-2">
            <!-- Image plus info -->
            <div class="d-flex">
              <div class="d-flex flex-grow-1 d-flex justify-content-between p-3 mx-2">
                <div class="border-right-line-add-card">
                  <h2 class="mb-3"><%= cuisine.name %></h2>
                  <div class="d-flex">
                    <%= link_to map_path(cuisine_id: cuisine.id, season: params[:season]) do %>
                      <div class="btn btn-yellow btn-yellow-smaller px-4">
                        <i class="fas fa-map-marker-alt"></i> See details
                      </div>
                    <% end %>
                  </div>
                </div>

                <div class="card-product-price-range">
                  <p class ="card-product-metric-title" title ="Ranking by attendance">Ranking </p>
                  <span class="d-block pl-3">
                    <span class="badge badge-warning badge-ranking"><%= cuisine.ranking %></span>
                </span>
                </div>

                <div class="card-product-attendance">
                  <p class ="card-product-metric-title" title="Average people by restaurant every month"> Av. Attendance</p>
                  <p><%=  cuisine.av_attendance(@city, params[:season]).floor %> people / mth</p>
                </div>

                <div class="card-product-rating">
                  <p class ="card-product-metric-title" title="Average rating of all restaurants of this cuisine">Rating</p>
                  <p><%= cuisine.av_rating.to_f %> / 5</p>
                </div>

                <div class="card-product-price-range">
                  <p class ="card-product-metric-title" title = "Average money spend by customer per visit">Price</p>
                  <p><%= cuisine.av_price_range %> $</p>
                </div>

                <div class="card-product-no_restaurants">
                  <p class ="card-product-metric-title" title="No restaurants of this cuisine in the city">No. restaurants</p>
                  <p class="px-4"><%= cuisine.no_restaurants %></p>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>

    <div class="col-6">
      <div class="mb-3 ml-4">
        <h1><strong>Attendance over time</strong></h1>
        <h4> in <%= @city.name %></h4>
      </div>
      <%= line_chart @cuisines_map.map { |cuisine| { name: cuisine[:name], data: cuisine[:data] }},
        height: '80%', points: false, legend: 'bottom' %>
    </div>

    <div >
    </div>
  </div>
  <p class = "text-right mt-3" style="font-size: 15px">*Click on the legend to change the selection</p>
</div>

app/views/trends/map.html.erb
<div class="row">
  <div class="col-6 mt-5">
    <%=  link_to graph_path(cuisine_id: params[:cuisine_id], season: params[:season]), class: 'small-cuisine-card-name-gray mx-5' do %>
      |<i class="fas fa-arrow-left"></i> Back
    <% end %>

    <div class="mx-5">
      <div class="alert alert-warning alert-yellow alert-no-float d-none">
        Cuisine type added to favorites.
        <button type="button" class="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <h1 class=" mt-5 mb-4">
        <strong><%= @cuisine.name %>  cuisine performance </strong>
      </h1>
      <h4>In <%= @city.name %> January to December</h4>



      <!-- additionnale metrics and comments -->
      <div class="">
        <table class="table table-map mt-4">
          <thead>
            <tr>
              <th scope="col">Metrics</th>
              <th scope="col"><%= @cuisine.name %> cuisine</th>
              <th scope="col">Top range Cuisine</th>
              <th scope="col">Mid range Cuisine</th>
            </tr>
          </thead>

          <tbody>
            <tr>

              <td>Av. Attendance</td>
              <td class="<%= @cuisine.av_attendance(@city,@season) > @threshold_attendance_top ? 'text-success':'text-warning' %>"><%=  @cuisine.av_attendance(@city,@season).floor%></td>
              <td><%= @threshold_attendance_top.floor %></td>
              <td><%= @threshold_attendance_bottom.floor %></td>
            </tr>
            <tr>

              <td>Rating</td>
              <td class="<%= @cuisine.av_rating > @average_top_rating ? 'text-success':'text-warning'%>"> <%=@cuisine.av_rating.round(2) %></td>
              <td><%= @average_top_rating.round(2) %></td>
              <td><%= @average_mid_rating.round(2) %></td>
            </tr>
            <tr>
              <td>Price</td>
              <td ><%= @cuisine.av_price_range %> $</td>
              <td><%= @average_top_price %> $</td>
              <td><%= @average_mid_price %> $</td>
            </tr>
            <tr>
              <td>No. Restaurants</td>
              <td class="<%= @cuisine.no_restaurants < @average_top_competitors ? 'text-success':'text-warning' %>"><%= @cuisine.no_restaurants %></td>
              <td><%= @average_top_competitors %></td>
              <td><%= @average_mid_competitors %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <!-- Button -->
      <div class="mt-4">
        <%= render 'shared/favorite_button', cuisine: @cuisine %>
      </div>
    </div> <!-- /col-6 -->
  </div>

  <!-- Map -->
  <div class="col-6" style="padding:0px;">
    <div
      id="map"
      style="width: 100%;height: calc(100vh - 70px);"
      data-markers="<%= @markers.to_json %>"
      data-restaurants="<%= @geojson.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/trends/results.html.erb
<div class="contain-page">
  <div class="containLoader">
    <div class="loadingBar-area">
      <div class="loadingBar">
        <div class="gradient"></div>
      </div>
    </div>
  </div>
</div>

<div class="d-flex">

  <!-- Cuisine not selected side menu 2/12 columns-->
  <div class="col-2 lg-container-card small-cuisine-card-container">
    <h3 class="results-rounded-card-header">Add from the Top ranked cuisines: </h3>
    <% @unselectedcuisines.each do |c| %>
      <%= top_cuisine_link_to c, @favoritecuisines, class: "small-cuisine-card-name-gray" do %>
        <div class="border-bottom-line-add-card d-flex <%= @favoritecuisines.map(&:cuisine).include?(c) ? 'selected' : '' %>">
          <span class="badge badge-warning flex-grow-0 badge-ranking ml-2 mr-2"><%= c.ranking %></span>

          <span class="flex-grow-1"><%= c.name %></span>

          <span class="plus-icon">
            <%= show_svg('plus-icon.svg') %>
          </span>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Show displayed cuisines and top orders buttons - 10/12 columns-->
  <div class="col-10 css-behaving-of-scrowling">
    <!-- buttons to order -->
    <div class="row rectangle-white-bar d-flex align-content-center px-3">
      <%#= link_to 'Name', results_path(selected_filter: 'name', query: 'name'),
        class: classes_for_menu('name') %>

      <div style ="padding-top: 4px"> Sort by :</div>
      <%= link_to 'Attendance', results_path(selected_filter: 'attendance', attendance: true),
        class: classes_for_menu('attendance') %>
      <%= link_to 'Rating', results_path(selected_filter: 'rating', metrics: 'av_rating'),
        class: classes_for_menu('rating') %>
      <%= link_to 'Price', results_path(selected_filter: 'price', metrics: 'av_price_range'),
        class: classes_for_menu('price') %>
      <%= link_to 'No. Restaurants', results_path(selected_filter: 'number', metrics: 'no_restaurants'),
        class: classes_for_menu('number') %>

    </div>

    <div class=" d-flex flex-column m-2 pt-1">
      <div class="text d-flex my-4  mx-2">
        <h4>Compare cuisines in <strong><%= @city.name %></strong> </h4>
        <%= link_to graph_path(season: @season), id:"compare-trend-button", class: 'btn btn-md btn-yellow ml-auto py-2 px-5' do%>
          <i class="fas fa-chart-area"></i> Trends comparison
        <% end %>
      </div>

      <!-- Card Product -->
      <div class="scroll-div">
        <% @favoritecuisines.each do |fc| %>
        <div class="card-product m-2">
          <!-- Image plus info -->
          <div class="d-flex">

            <!-- Image -->
            <%= image_tag fc.cuisine.photo %>
            <!-- Info -->
            <div class="d-flex flex-grow-1 d-flex justify-content-between p-3 mx-2">
              <!-- Cuisine name 2/12 columns-->
              <div class="border-right-line-add-card col-2">
                <h2 class="mb-3"><%= fc.cuisine.name %></h2>
                <!-- <div classs="d-flex"> -->

                  <%#= link_to map_path(cuisine_id: fc.cuisine.id, season: @season) do %>
                    <!-- <div class="btn btn-yellow btn-yellow-smaller px-4">
                      <i class="fas fa-map-marker-alt"></i> Select cuisine
                    </div> -->
                  <%# end %>
                  <%#= link_to favorite_cuisine_compare_path(favorite_cuisine_id: fc.id) do %>
                    <!-- <div class="btn btn-outline-yellow btn-yellow-smaller">
                      <i class="fas fa-chart-area"></i> Compare
                    </div> -->
                  <%# end %>

                <!-- </div> -->
              </div>


              <!-- Cuisine ranking 2/12 columns-->
              <div class="card-product-price-range col-2 ml-3">
                <span class ="card-product-metric-title" title ="Ranking by attendance">Ranking</span>
                <span class="d-block pl-2">
                  <span class="badge badge-warning badge-ranking"><%= fc.cuisine.ranking %></span>
                </span>
              </div>

              <!-- Cuisine attendance 2/12 columns-->
              <div class="card-product-attendance col-2">
                <span class ="card-product-metric-title" title="Average people by restaurant every month"> Av. Attendance </span>
                <p><%=  fc.cuisine.av_attendance(@city,@season).floor%> people / mth</p>
              </div>

              <!-- Cuisine rating 2/12 columns-->
              <div class="card-product-rating col-2">
                <span class ="card-product-metric-title" title="Average rating of all restaurants of this cuisine">Rating </span>
                <!-- <p><%#=raw "<i class='fas fa-star icon-color-mustard'></i>" * fc.cuisine.av_rating %></p> -->
                <p><%=fc.cuisine.av_rating.to_f %> / 5</p>
              </div>


                <!-- IH comment:  passing the cuisine_id which will be used in the map view -->

                <%#= link_to map_path(cuisine_id: fc.cuisine.id, season: @season) do %>
                  <!-- <i class="fas fa-map-marker-alt icon-color-mustard"></i> Find location -->
                <%# end %>

                <!-- Cuisine price-range 2/12 columns-->
                <div class="card-product-price-range col-2">
                  <span class ="card-product-metric-title" title = "Average money spend by customer per visit">Price </span>
                  <p><%= fc.cuisine.av_price_range %> $</p>
                </div>

                <!-- Cuisine no. restaurants 2/12 columns-->
                <div class="card-product-no_restaurants col-2">
                  <span class ="card-product-metric-title" title="No restaurants of this cuisine in the city">No. restaurants </span>
                  <p class="pl-5"><%= fc.cuisine.no_restaurants %></p>
                </div>

              </div>
              <!-- Delete info -->
              <div class="flex-shrink-1 m-2">
                <%= link_to favorite_cuisine_path(fc.id), method: :delete, class: "cuisine-comparison-horizontal-card-button_delete" do %>
                  <div></div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="">
      <!-- cuisine for comparison -->
      <% @comparisoncuisines.each do |fc| %>
        <%= fc.cuisine.name %>
        <%= link_to favorite_cuisine_uncompare_path(fc.id) do %>
          <i class="fa fa-trash" ></i>
        <% end %>
      <% end %>
    </div>

        <%#= @cuisines.first(14).sum  /14 %>


  </div>

</div>