config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cuisines, only: [:index]
  resources :matches, only: [:index, :create, :destroy]

  delete '/cuisines/:cuisine_id/destroy_match', to: 'matches#destroy', as: :match_destroy

  resources :favorite_cuisines, only: [:create, :destroy] do
    collection do #removing the ID in the url <> member which shos the ID
      get 'add'
    end
    get 'compare'
    get 'uncompare'
  end

  get 'results', to:'trends#results'
  get 'comparison', to:'pages#comparison'
  get 'map', to:'trends#map'
  get 'graph', to:'trends#graph'
end

app/views/shared/_cards.html.erb
<div class="card-cuisine-<%= cuisine.id %>">
  <%= cuisine.name %>
</div>

app/views/shared/_favorite_button.html.erb
<%= content_tag :div, id: "btn-favorite-active-#{@cuisine.id}",
  style: "display: #{current_user.matched?(@cuisine) ? 'block' : 'none'}" do %>
  <%= link_to match_destroy_path(@cuisine),
    method: :delete, class: 'btn btn-lg btn-yellow px-4', remote: true do %>
    <i class="fas fa-heart"></i> Favorite
  <% end %>
<% end %>

<%= content_tag :div, id: "btn-favorite-#{@cuisine.id}",
  style: "display: #{current_user.matched?(@cuisine) ? 'none' : 'block'}" do %>
  <%= link_to matches_path(cuisine_id: @cuisine.id, city: @city, season: @season),
    method: :post, class: 'btn btn-lg btn-outline-yellow px-4', remote: true do %>
    <i class="far fa-heart"></i> Favorite
  <% end %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-poppin">
  <!-- LOGO -->
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>

  <div class="nav-content">
    <!-- OTHER PAGES LINKS -->
    <div class="nav-links">
      <%= link_to "Home", root_path, class: "nav-link-font"%>
      <%= link_to "About us", "#", class: "nav-link-font"%>
      <%= link_to "Contact", "#", class: "nav-link-font"%>
    </div>

    <div class="nav-links">
      <% if user_signed_in? %>
        <%= link_to 'Favorites', matches_path, class: 'nav-link-font' %>
        <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link-font" %>
        <!-- LOGIN SIGNIN -->
      <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link-font"%>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link-font"%>
      <% end %>
    </div>
  </div>
</nav>