config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cuisines, only: [:index]
  resources :matches, only: [:index, :create, :destroy]

  delete '/cuisines/:cuisine_id/destroy_match', to: 'matches#destroy', as: :match_destroy

  resources :favorite_cuisines, only: [:create, :destroy] do
    collection do #removing the ID in the url <> member which shos the ID
      get 'add'
    end
    get 'compare'
    get 'uncompare'
  end

  get 'results', to:'trends#results'
  get 'comparison', to:'pages#comparison'
  get 'map', to:'trends#map'
  get 'graph', to:'trends#graph'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :user
  belongs_to :cuisine

  validates :user, :cuisine, presence: true
  validates :user, uniqueness: { scope: :cuisine }
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def create
    @cuisine = Cuisine.find(params[:cuisine_id])

    current_user.matches.where(cuisine: @cuisine).first_or_create do |match|
      match.city = params[:city],
      match.season = params[:season]
    end
  end

  def destroy
    if (params[:cuisine_id])
      @cuisine = Cuisine.find(params[:cuisine_id])
      @match = current_user.matches.find_by(cuisine: @cuisine)
    else
      @match = current_user.matches.find(params[:id])
    end

    @match.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to matches_path }
    end
  end
end

app/views/matches/create.js.erb
var activeButton = document.getElementById('btn-favorite-active-<%= @cuisine.id %>');
var button = document.getElementById('btn-favorite-<%= @cuisine.id %>');

activeButton.style.display = 'block';
button.style.display = 'none';

var alert = document.getElementsByClassName('alert-yellow')[0];
alert.classList.remove('d-none');
alert.classList.add('animated', 'flipInX');

var alertButton = alert.querySelector('.close');

var hideAlert = () => {
  alert.classList.remove('animated', 'flipInX');
  alert.classList.add('animated', 'fadeOut');
}

alertButton.addEventListener('click', () => {
  hideAlert();
});


setTimeout(() => {
  hideAlert();
}, 3000);

app/views/matches/destroy.js.erb
var activeButton = document.getElementById('btn-favorite-active-<%= @cuisine.id %>');
var button = document.getElementById('btn-favorite-<%= @cuisine.id %>');

activeButton.style.display = 'none';
button.style.display = 'block';

app/views/matches/index.html.erb
<div class="container mt-5">
  <h1><strong>My favorites</strong></h1>
  <h4 class="mb-5 muted">Cuisines in <strong>Sydney</strong> for <strong>January</strong> - <strong>December</strong></h4>

  <% @matches.each do |match| %>
    <div class="card-product m-2">
      <!-- Image plus info -->
      <div class="d-flex">
        <%= image_tag match.cuisine.photo %>

        <div class="d-flex flex-grow-1 d-flex justify-content-between p-3 mx-2">
          <div class="border-right-line-add-card">
            <h2 class="mb-3"><%= match.cuisine.name %></h2>
            <div class="d-flex">
              <%= link_to map_path(cuisine_id: match.cuisine.id, season: match.season) do %>
                <div class="btn btn-yellow btn-yellow-smaller px-4">
                  <i class="fas fa-map-marker-alt"></i> Show on map
                </div>
              <% end %>
            </div>
          </div>

          <div class="card-product-price-range ml-3">
            <span class ="card-product-metric-title" title ="Ranking by attendance">Ranking</span>
            <span class="d-block pl-2" >
              <span class="badge badge-warning badge-ranking"> <%= match.cuisine.ranking %></span>
            </span>
          </div>

          <div class="card-product-attendance">
            <span class ="card-product-metric-title" title="Average people by restaurant every month"> Av. Attendance </span>
            <p><%=  match.cuisine.av_attendance(match.city, match.season).floor %> people / mth</p>
          </div>

          <div class="card-product-rating">
            <span class ="card-product-metric-title" title="Average rating of all restaurants of this cuisine">Rating </span>
            <p><%= match.cuisine.av_rating.to_f %> / 5</p>
          </div>

          <div class="card-product-price-range">
            <span class ="card-product-metric-title" title = "Average money spend by customer per visit">Price </span>
            <p><%= match.cuisine.av_price_range %> $</p>
          </div>

          <div class="card-product-no_restaurants">
            <span class ="card-product-metric-title" title="No restaurants of this cuisine in the city">No. restaurants </span>
            <p class="pl-5
            4"><%= match.cuisine.no_restaurants %></p>
          </div>

          <div class="flex-shrink-1 ">
            <%= link_to match_path(match), method: :delete, class: "cuisine-comparison-horizontal-card-button_delete" do %>
              <div></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>